name: Compilation Windows PSXImager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Recupere les sources
      uses: actions/checkout@v4

    - name: Installe le compilateur Windows pour Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Compile les fichiers EXE pour Windows
      run: |
        x86_64-w64-mingw32-gcc -O2 src/psxrip.c -o psxrip.exe
        x86_64-w64-mingw32-gcc -O2 src/psxbuild.c -o psxbuild.exe
        x86_64-w64-mingw32-gcc -O2 src/psxinject.c -o psxinject.exe

    - name: Livre les EXE
      uses: actions/upload-artifact@v4
      with:
        name: psximager-windows
        path: |
          psxrip.exe
          psxbuild.exe
          psxinject.exe
